# Generated by Django 2.2.13 on 2022-07-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_billingaddress_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='zip',
        ),
    ]
