# Generated by Django 2.2.13 on 2022-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220711_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'Smart'), ('M', 'Medium')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
