# Generated by Django 2.2.13 on 2022-07-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
