# Generated by Django 2.2.13 on 2022-07-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
