# Generated by Django 2.2.13 on 2022-07-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20220714_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Product'),
            preserve_default=False,
        ),
    ]
