# Generated by Django 2.2.13 on 2022-07-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
